CREATE TABLE usuarios (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR2(255) NOT NULL UNIQUE,
  password_hash VARCHAR2(255) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE perfiles_caninos (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id NUMBER NOT NULL,
  nombre VARCHAR2(100) NOT NULL,
  raza VARCHAR2(100),
  fecha_nacimiento DATE,
  peso_actual_kg NUMBER(5,2),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_perfiles_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE bitacora_salud_entrenamiento (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  perfil_id NUMBER NOT NULL,
  fecha_registro DATE DEFAULT SYSDATE,
  categoria VARCHAR2(120) NOT NULL,
  gramos_alimento_diario NUMBER(6,2),
  observaciones VARCHAR2(1000),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_bitacora_perfil FOREIGN KEY (perfil_id) REFERENCES perfiles_caninos(id) ON DELETE CASCADE
);

CREATE INDEX idx_perfiles_usuario ON perfiles_caninos (usuario_id);
CREATE INDEX idx_bitacora_perfil ON bitacora_salud_entrenamiento (perfil_id);
